#!/usr/bin/env python3
"""Generate the search engine's one-code-point Unicode tables.

Inputs are the official Unicode Character Database CaseFolding.txt and
UnicodeData.txt files from the same release. Example:
  python tests/tools/generate_unicode_search_data.py CaseFolding.txt UnicodeData.txt \
      apps/neo_editor/model/unicode_search_data.h
"""

from __future__ import annotations

import re
import sys
import hashlib
from pathlib import Path

UCD_VERSION = "18.0.0"
CASE_FOLDING_URL = f"https://www.unicode.org/Public/{UCD_VERSION}/ucd/CaseFolding.txt"
UNICODE_DATA_URL = f"https://www.unicode.org/Public/{UCD_VERSION}/ucd/UnicodeData.txt"
CASE_FOLDING_SHA256 = "A004797658A457BEC4DC11683E39F69249EA3B595B752DBEA6721C4C9F587B0D"
UNICODE_DATA_SHA256 = "0736451DE439AE7BAF1425136617DA495E09EE5AFBE6E394374DB7009EA08950"


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as source:
        for block in iter(lambda: source.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest().upper()


def read_folds(path: Path) -> tuple[str, list[tuple[int, int]]]:
    text = path.read_text(encoding="utf-8")
    version_match = re.search(r"^# CaseFolding-([0-9]+(?:\.[0-9]+)*)", text, re.MULTILINE)
    if not version_match:
        raise ValueError(f"{path}: missing CaseFolding version header")
    folds = []
    for line in text.splitlines():
        data = line.split("#", 1)[0].strip()
        if not data:
            continue
        fields = [field.strip() for field in data.split(";")]
        if len(fields) < 3 or fields[1] not in {"C", "S"}:
            continue
        mapping = fields[2].split()
        if len(mapping) != 1:
            raise ValueError(f"{path}: non-simple C/S mapping: {line}")
        source, target = int(fields[0], 16), int(mapping[0], 16)
        if source != target:
            folds.append((source, target))
    folds.sort()
    version = version_match.group(1)
    if version != UCD_VERSION:
        raise ValueError(f"{path}: expected Unicode {UCD_VERSION}, got {version}")
    return version, folds


def read_word_ranges(path: Path) -> list[tuple[int, int]]:
    intervals: list[tuple[int, int]] = []
    pending: tuple[int, str] | None = None
    for line in path.read_text(encoding="utf-8").splitlines():
        fields = line.split(";")
        cp = int(fields[0], 16)
        name, category = fields[1], fields[2]
        if name.endswith(", First>"):
            pending = (cp, category)
            continue
        if name.endswith(", Last>"):
            if pending is None or pending[1] != category:
                raise ValueError(f"{path}: unmatched UnicodeData range: {line}")
            first, _ = pending
            pending = None
            if category.startswith(("L", "M", "N")) or category == "Pc":
                intervals.append((first, cp))
            continue
        if category.startswith(("L", "M", "N")) or category == "Pc":
            intervals.append((cp, cp))
    if pending is not None:
        raise ValueError(f"{path}: unfinished UnicodeData range")

    intervals.sort()
    merged: list[list[int]] = []
    for first, last in intervals:
        if merged and first <= merged[-1][1] + 1:
            merged[-1][1] = max(merged[-1][1], last)
        else:
            merged.append([first, last])
    return [(first, last) for first, last in merged]


def emit(output: Path, version: str, folds: list[tuple[int, int]],
         ranges: list[tuple[int, int]], case_hash: str, unicode_hash: str) -> None:
    lines = [
        "// Generated by tests/tools/generate_unicode_search_data.py.",
        f"// Unicode Character Database {version} final release; see tests/tools/UNICODE-LICENSE.txt.",
        f"// CaseFolding.txt: {CASE_FOLDING_URL}",
        f"// SHA-256: {case_hash}",
        f"// UnicodeData.txt: {UNICODE_DATA_URL}",
        f"// SHA-256: {unicode_hash}",
        "#pragma once",
        "#include <array>",
        "#include <cstdint>",
        "",
        "namespace neo::search::unicode_data {",
        "struct Fold { std::uint32_t from; std::uint32_t to; };",
        "struct Range { std::uint32_t first; std::uint32_t last; };",
        f"inline constexpr std::array<Fold, {len(folds)}> folds{{{{",
    ]
    lines.extend(f"    Fold{{0x{a:X}, 0x{b:X}}}," for a, b in folds)
    lines.extend(["}};", f"inline constexpr std::array<Range, {len(ranges)}> wordRanges{{{{"])
    lines.extend(f"    Range{{0x{a:X}, 0x{b:X}}}," for a, b in ranges)
    lines.extend(["}};", "} // namespace neo::search::unicode_data", ""])
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines), encoding="utf-8", newline="\n")


def main() -> int:
    if len(sys.argv) != 4:
        print(__doc__.strip(), file=sys.stderr)
        return 2
    case_folding, unicode_data, output = map(Path, sys.argv[1:])
    case_hash, unicode_hash = sha256(case_folding), sha256(unicode_data)
    if case_hash != CASE_FOLDING_SHA256:
        raise ValueError(f"{case_folding}: unexpected SHA-256 {case_hash}; expected pinned Unicode {UCD_VERSION} data")
    if unicode_hash != UNICODE_DATA_SHA256:
        raise ValueError(f"{unicode_data}: unexpected SHA-256 {unicode_hash}; expected pinned Unicode {UCD_VERSION} data")
    version, folds = read_folds(case_folding)
    ranges = read_word_ranges(unicode_data)
    emit(output, version, folds, ranges, case_hash, unicode_hash)
    print(f"Unicode {version}: {len(folds)} folds, {len(ranges)} word ranges -> {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
