set(NEO_EDITOR_VERSION "0.1.1" CACHE STRING "NeoEditor version (independent of EUI-NEO).")
if(NOT NEO_EDITOR_VERSION MATCHES "^(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)\\.(0|[1-9][0-9]*)(-[0-9A-Za-z]+([.-][0-9A-Za-z]+)*)?$")
    message(FATAL_ERROR "NEO_EDITOR_VERSION must be major.minor.patch with an optional prerelease suffix.")
endif()
set(NEO_EDITOR_VERSION_MAJOR "${CMAKE_MATCH_1}")
set(NEO_EDITOR_VERSION_MINOR "${CMAKE_MATCH_2}")
set(NEO_EDITOR_VERSION_PATCH "${CMAKE_MATCH_3}")
foreach(part MAJOR MINOR PATCH)
    if(NEO_EDITOR_VERSION_${part} GREATER 65535)
        message(FATAL_ERROR "NeoEditor numeric version fields must fit PE VERSIONINFO (0..65535).")
    endif()
endforeach()
set(NEO_EDITOR_FILE_VERSION "${NEO_EDITOR_VERSION_MAJOR}.${NEO_EDITOR_VERSION_MINOR}.${NEO_EDITOR_VERSION_PATCH}.0")
set(NEO_EDITOR_FILE_VERSION_RC "${NEO_EDITOR_VERSION_MAJOR},${NEO_EDITOR_VERSION_MINOR},${NEO_EDITOR_VERSION_PATCH},0")
set(NEO_EDITOR_VERSION_FLAGS "0x0L")
if(NEO_EDITOR_VERSION MATCHES "-")
    set(NEO_EDITOR_VERSION_FLAGS "0x2L")
endif()
set(NEO_EDITOR_GENERATED_INCLUDE_DIR "${CMAKE_CURRENT_BINARY_DIR}/generated/neoeditor")
file(MAKE_DIRECTORY "${NEO_EDITOR_GENERATED_INCLUDE_DIR}")
configure_file("${CMAKE_CURRENT_SOURCE_DIR}/cmake/NeoEditorVersion.h.in"
    "${NEO_EDITOR_GENERATED_INCLUDE_DIR}/neo_editor_version_generated.h" @ONLY)
set(NEO_EDITOR_VERSION_RC "${CMAKE_CURRENT_BINARY_DIR}/neo_editor_version.rc")
configure_file("${CMAKE_CURRENT_SOURCE_DIR}/cmake/NeoEditorVersion.rc.in"
    "${NEO_EDITOR_VERSION_RC}" @ONLY)
